task:
  name: "Setting Up, Syncing, Building and Uploading...."
  timeout_in: 240m  
  container:
      image: ubuntu-latest
      cpu: 8
      memory: 32G
        
  Build-Env-Setup_script:
       - export DEBIAN_FRONTEND=noninteractive
       - apt update
       - apt install sudo
       - DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tzdata
       - ln -sf /usr/share/zoneinfo/Asia/Kolkata /etc/localtime
       - apt-get install -y tzdata
       - dpkg-reconfigure --frontend noninteractive tzdata
       - sudo apt update -y && sudo apt install git aria2 curl wget rsync zip unzip lzma cpio ccache clang -y
       - sudo apt install python3 -y
       - sudo ln -sf /usr/bin/python3 /usr/bin/python
       - git config --global user.name "Hasajapathirana"
       - git config --global user.email "hasajapathirana2011@gmail.com"
       - git clone https://github.com/akhilnarang/scripts.git ~/scripts
       - cd ~/scripts
       - sudo bash setup/android_build_env.sh
       - cd ~
  
  Storage-Checker_script:
      - df -h
      - lsblk
      - ls -l -a -h
  
  Sync_script:
      - echo "============================"
      - echo "Syncing The Sources...."
      - echo "============================"
      - mkdir ~/UB
      - cd ~/UB
      - repo init -u https://github.com/Halium/android -b halium-7.1 --depth=1
      - cd ~/UB
      - repo sync -c -j700
      - echo "============================"
      - echo "Syncing Complete!"
      - echo "============================"

  Build_script:
      - echo "============================"
      - echo "Starting the Build..."
      - echo "============================"
      - cd ~/UB
      - git clone https://github.com/pstglia/android_device_samsung_core33g.git device/samsung/core33g
      - source build/envsetup.sh
      - export ALLOW_MISSING_DEPENDENCIES=true
      - brunch core33g
  Upload_script:
      - echo "============================"
      - echo "Uploading the Build..."
      - echo "============================"
      - cd out/target/product/core33g
      - ls -lh
      - pwd
      - chmod 777 *
      - curl --upload-file *zip* https://transfer.sh | tee link.txt && echo " "
      - echo " "
      - echo "============================"
      - echo "Build Uploaded!"
      - echo "Please see the link Below-  "
      - echo "----------------------------"
      - cat link.txt && echo " "
      - echo "============================"
